name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: subscription-shepard
  REGION: us-central1
  SERVICE_NAME: subscription-shepard
  GAR_REPOSITORY: cloud-run-source-deploy
  IMAGE_NAME: subscription-shepard

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/210493677553/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-deployer@subscription-shepard.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and Push Container Image
        run: |
          IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to Cloud Run
        run: |
          IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=$IMAGE_URI \
            --region=${{ env.REGION }} \
            --service-account=subscription-shepard-runtime@${{ env.PROJECT_ID }}.iam.gserviceaccount.com \
            --allow-unauthenticated
